---
title: "Hipp_Elwha_Exploratory"
author: "Sylvia Hipp"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---


```{r Setup Environment}

library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
library(rvest)
library(dataRetrieval)
library(tidycensus)
library(glue)

here()

```


## Notes

Goal: examine impact of two Elwha dam removals on coastal organisms


# Data Availability

### Elwha River


### Elwha Estuary RSET (Sediment)

```{r Sediment Data Exploration}

# Sediment deposition in the Elwha River estuary, Washington, measured on rod surface elevation tables (RSETs) from 2011 to 2014

elwha_sediment_raw <- read_csv(here("Data/Raw/Elwha_Estuary_RSET_Sediment/Elwha_estuary_RSETs_2011-2014.csv")) %>%   tibble() %>% 
  clean_names

summary(elwha_sediment_raw)

elwha_sediment <- elwha_sediment_raw %>% 
  mutate(date_measured = mdy(date_measured), 
         average_distance = as.numeric(average_distance), 
         set_number = as.factor(set_number)) 

# 15 distinct sites represented given longitude and latitude of each site
# 10 observations from each site
elwha_sediment %>%  
  count(set_number)

ggplot(elwha_sediment) +
  geom_point(aes(x = date_measured, y = average_distance, color = set_number))


```

### Elwha Daily Sediment
```{r}

elwha_daily_sediment_raw <- read_csv(paste0(here("Data/Raw/Elwha_DailySediment_2011_2016/"),
                                            "Elwha_DailySedimentLoads_2011to2016 (1).csv")) %>% 
  clean_names()

elwha_daily_sediment <- elwha_daily_sediment_raw %>%
  mutate(day = mdy(day))

ggplot(elwha_daily_sediment) + 
  geom_point(aes(x = day, y = daily_discharge_m3_s))

ggplot(elwha_daily_sediment) + 
  geom_point(aes(x = day, y = daily_ssc_mg_l)) + 
  scale_x_date(date_breaks = "6 months", 
               date_labels = "%m-%y")

```


### Time series data

Pull data for USGS site no. 12045500 (Elwha River)
Interest in discharge and gage height
```{r timeseries}

# # set parameters
# site_number <- "USGS-12045500"
# stat_code <- "00003"  # mean
# p_code_discharge <- "00060"
# p_code_gage_height <- "00065"
# 
# start_date <- "2010-01-01"
# end_date <- "2020-01-01"
# 
# 
# # connect to API to read in daily discharge data
# daily_discharge <- read_waterdata_daily(
#   monitoring_location_id = site_number,
#   parameter_code = p_code_discharge,
#   statistic_id = stat_code,
#   time = c(start_date, end_date),
#   skipGeometry = TRUE) %>%
#   select("monitoring_location_id", "time", "unit_of_measure",
#          "value", "parameter_code")

site_number <- "12045500"
param_discharge <- "00060"
param_gage_height <- "00065"

read_continuous_data <- function(parameter, site_no){
  data_url <- paste0("https://nwis.waterservices.usgs.gov/nwis/iv/",
                     glue("?sites={site_no}&agencyCd=USGS&"),
                     "startDT=2008-01-01T00:00:00.000-08:00&",
                     "endDT=2016-12-31T23:59:59.999-08:00",
                     glue("&parameterCd={parameter}&format=rdb"))
  
  param_name <- case_when(parameter == "00065" ~ "gage_height_ft", 
                          parameter == "00060" ~ "discharge_cfs")
  
  df_raw <- read.table(
    file = data_url, 
    skip = 26, 
    header = TRUE, 
    sep = "\t") 
  
  return(df_raw[2:nrow(df_raw),]) # remove first row that doesn't contain data
  
}

gage_height_raw <- read_continuous_data(param_gage_height, site_number)
discharge_raw <- read_continuous_data(param_discharge, site_number)

gage_height_df <- gage_height_raw %>% 
  clean_names() %>% 
  rename("gage_height_ft" = x150692_00065) %>% 
  select(-contains("00065")) %>% 
  mutate(datetime = as.POSIXct(datetime, tz = "PST"), 
         date = as.Date(datetime), 
         gage_height_ft = as.numeric(gage_height_ft)) 

discharge_df <- discharge_raw %>% 
  clean_names() %>% 
  rename("discharge_cfs" = x150691_00060) %>% 
  select(-contains("00060")) %>% 
  mutate(datetime = as.POSIXct(datetime, tz = "PST"), 
         date = as.Date(datetime), 
         discharge_cfs = as.numeric(discharge_cfs))
  
ggplot()+
  geom_line(data = gage_height_df, aes(x = datetime, y = gage_height_ft)) 

ggplot()+
  geom_line(data = gage_height_df, aes(x = datetime, y = gage_height_ft))

## confirm daily data matches the continuous data
# ggplot() + 
#   geom_line(data = discharge_df %>% 
#               mutate(date = as.Date(datetime)) %>% 
#               group_by(date) %>% 
#               summarize(avg_discharge = mean(discharge_cfs)) %>% 
#               ungroup(),
#             aes(x = date, y = avg_discharge)) + 
#   geom_line(data = daily_discharge, aes(x = time, y = value), 
#             color = "red")
  
```
