---
title: "Kukula_Elwha_Exploratory"
author: "Kaitlyn Kukula"
date: "`r Sys.Date()`"
output: pdf_document
---

## NOTES

The goal of this study is to perform a general review of coastal organisms following the removal of two dams from the Elwha River in Washington. Some interesting questions to consider could be the use of eDNA for tracking fish movements or determining food chain transformations. 

USGS Report (PDF in folder): chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://pubs.usgs.gov/sir/2011/5120/pdf/sir20115120.pdf

A general structure of the study could include:
1. System analysis: streamflow at available USGS gage site, estuary sediment transport
2. Comparing water quality metrics before and after dam removal
   Literature review may be required to put these values in context
3. Mapping and comparing species distribution/abundance before and after dam removal
4. Mapping and comparing eDNA and species distribution/abundance

Available data:
- eDNA shedding from live and dead fish
- Estuarian fish
- Estuarian riparian veg abundance
- Estuarian riparian veg richness
- Estuarian sediment
- Estuarian WQ
- eDNA post-removal

Data we need to gather or find:
- USGS Gage Station #12045500
- USGS Gage Station #12044900
- Watershed spatial data

Some maps I think would be useful:
Map 1. Elwha River watershed including major tributaries, dams, USGS monitoring stations, and an inset map showing the general location in Washington
Map 2-n. Sample collection sites for organism studies. This could be an interactive map.
Map n+1: Might be interested in showing the spatial species distributions if we find anything of note? This could be an interactive map. 

Some figures I think would be useful:
- Streamflow at both sites as a function of time
- Species comparisons before and after dam removal
