---
title: "Discharge_GageHeight"
author: "Sylvia Hipp"
date: "`r Sys.Date()`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

# Set Up Environment

```{r Setup Environment}

library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
library(rvest)
library(dataRetrieval)
library(glue)

# check current working directory
here()

```

```{r}
# set theme

kukulahipp_theme <- theme_classic() +
  theme(plot.title = element_text(size = 11, hjust = 0.5, face = "bold"), #Adjust title
        axis.text.x = element_text(size = 9), # Adjust x-axis values
        axis.text.y = element_text(size = 9), # Adjust y-axis values
        axis.title.x = element_text(size = 10.5, face = "bold"), # Adjust x-axis title
        axis.title.y = element_text(size = 10.5, face = "bold"), # Adjust y-axis title
        legend.position = "bottom", # Define legend position
        legend.text = element_text(size = 9), # Define legend entry sizes
        legend.title = element_text(size = 9)) # Define legend name sizes
theme_set(kukulahipp_theme)
```


# Pull Raw Data and Initial Wrangling

## Define USGS Site and Metric Parameters

```{r}
site_number_mid <- "12045500"
site_number_above <- "12044900"
site_number_below <- "12046260"
param_discharge <- "00060"
param_gage_height <- "00065"

start <- "2008-01-01"
end <- "2016-12-31"

```

## Read in Raw data

Define function to scrape data from USGS site
```{r}

read_continuous_data <- function(parameter, site_no, start, end){
  data_url <- glue(paste0("https://nwis.waterservices.usgs.gov/nwis/iv/?",
                          "sites={site_no}&agencyCd=USGS&",
                          "startDT={start}T00:00:00.000-08:00&",
                          "endDT={end}T23:59:59.999-08:00",
                          "&parameterCd={parameter}&format=rdb"))
  
  param_name <- case_when(parameter == "00065" ~ "gage_height_ft", 
                          parameter == "00060" ~ "discharge_cfs")
  
  df_raw <- read.table(file = data_url, 
                       skip = 26, 
                       header = TRUE, 
                       sep = "\t") %>% 
    tibble() %>% 
    select(-c(6)) %>% 
    rename(!!param_name:=5)
  
  return(df_raw[2:nrow(df_raw),]) # remove first row that doesn't contain data
}

```

Read in Raw Data
```{r}

gage_height_mid_raw <- read_continuous_data(param_gage_height, site_number_mid, 
                                        start, end)
discharge_mid_raw <- read_continuous_data(param_discharge, site_number_mid, 
                                      start, end)

gage_height_above_raw <- read_continuous_data(param_gage_height, site_number_above, 
                                              start, end)
discharge_above_raw <- read_continuous_data(param_discharge, site_number_above, 
                                            start, end)

```

## Data Wrangling

Prepare datasets at the daily level
```{r}

wrangle_data <- function(df_raw, param){
  avg_var = paste0("avg_", param)
  
  df <- df_raw %>% 
    mutate(datetime = as.POSIXct(datetime, tz = "PST"),
           date = as.Date(datetime), 
           !!param := as.numeric(!!sym(param)), 
           site_location = case_when(site_no == "12044900" ~ "above", 
                                     site_no == "12045500" ~ "mid")) %>% 
    group_by(date, site_no, site_location) %>% 
    summarize(!!avg_var := mean(!!sym(param), na.rm = TRUE)) %>% 
    ungroup()
  
  return(df)
}

gage_height_df <- bind_rows(
  wrangle_data(gage_height_above_raw, "gage_height_ft"), 
  wrangle_data(gage_height_mid_raw, "gage_height_ft"))
  
discharge_df <- bind_rows(
  wrangle_data(discharge_above_raw, "discharge_cfs"), 
  wrangle_data(discharge_mid_raw, "discharge_cfs"))

ggplot(gage_height_df %>% filter(year(date)>2011, site_location=="above")) + 
  geom_line(aes(x = date, y = avg_gage_height_ft, color = site_location))

ggplot(discharge_df) + 
  geom_line(aes(x = date, y = avg_discharge_cfs, color = site_location))

```

Prepare dataset for timeseries analysis
```{r}
# visualize trends for gage height and discharge
ggplot(data = discharge_df) + 
  geom_line(aes(x = date, y = avg_discharge_cfs)) + 
  labs(y = "Average Daily Discharge (CFS)", 
       x = NULL)

ggplot(data = gage_height_df) + 
  geom_line(aes(x = date, y = avg_gage_height_ft)) + 
  labs(y = "Average Gage Height (ft)", 
       x = NULL)

# object with all dates between start and end
dates <- seq.Date(ymd(start), ymd(end), by = "day") %>% 
  as_tibble() %>% 
  rename("date" = value)

# combine data into one dataframe
ts_df <- dates %>% 
  left_join(discharge_df, by = "date") %>%  # 130 days missing 
  left_join(gage_height_df, by = "date") %>% 
  # use linear interpolation to fill in gaps
  mutate(avg_discharge_cfs = zoo::na.approx(avg_discharge_cfs)) 

```

## Time Series Analysis

Prepare timeseries objects
```{r}
first_month <- month(first(ts_df$date))
first_year <- year(first(ts_df$date))

# Create time series objects
discharge_ts <- ts(ts_df$avg_discharge_cfs, 
                   start = c(first_year, first_month), 
                   frequency = 365)
gage_height_ts <- ts(ts_df$avg_gage_height_ft, 
                     start = c(first_year, first_month), 
                     frequency = 365)

```


